import React, { useEffect } from 'react';
import { BrowserRouter as Router, Routes, Route, Navigate } from 'react-router-dom';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { useAppStore } from '@/store/main';

// Import views - this will be dynamically generated by your system
import UV_Login from '@/components/views/UV_Login';
import UV_Dashboard from '@/components/views/UV_Dashboard';
import UV_WorkoutTemplates from '@/components/views/UV_WorkoutTemplates';


const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      staleTime: 5 * 60 * 1000, // 5 minutes
      retry: 1,
    },
  },
});

// Loading component
const LoadingSpinner: React.FC = () => (
  <div className="min-h-screen flex items-center justify-center bg-gray-50">
    <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600"></div>
  </div>
);

// CRITICAL: Correct Zustand selector pattern - NO object destructuring
const ProtectedRoute: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  // CORRECT: Individual selectors to avoid infinite loops
  const isAuthenticated = useAppStore(state => state.authentication_state.authentication_status.is_authenticated);
  const isLoading = useAppStore(state => state.authentication_state.authentication_status.is_loading);
  
  if (isLoading) {
    return <LoadingSpinner />;
  }
  
  if (!isAuthenticated) {
    return <Navigate to="/login" replace />;
  }
  
  return <>{children}</>;
};



const App: React.FC = () => {
  // CRITICAL: Individual selectors, no object destructuring
  const isLoading = useAppStore(state => state.authentication_state.authentication_status.is_loading);
  const initializeAuth = useAppStore(state => state.initialize_auth);
  
  useEffect(() => {
    // Initialize auth state when app loads
    initializeAuth();
  }, [initializeAuth]);
  
  if (isLoading) {
    return <LoadingSpinner />;
  }
  
  return (
    <Router>
      <QueryClientProvider client={queryClient}>
        <div className="App min-h-screen flex flex-col">
          {/* <GV_NavTop /> */}
          <main className="flex-1">
            <Routes>
              {/* Public Routes */}
              {/* <Route path="/" element={<UV_Landing />} /> */}
              <Route 
                path="/login" 
                element={
                 
                    <UV_Login />
                 
                } 
              />
              
              {/* Protected Routes */}
              <Route 
                path="/dashboard" 
                element={
                  <ProtectedRoute>
                    <UV_Dashboard />
                  </ProtectedRoute>
                } 
              />
              
              <Route 
                path="/workouts" 
                element={
                  <ProtectedRoute>
                    <div className="min-h-screen bg-gray-50">
                      <nav className="bg-white shadow mb-6">
                        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                          <div className="flex justify-between h-16">
                            <div className="flex items-center">
                              <h1 className="text-xl font-semibold text-gray-900">Workouts</h1>
                            </div>
                            <div className="flex items-center space-x-4">
                              <a href="/dashboard" className="text-gray-700 hover:text-gray-900 px-3 py-2 rounded-md text-sm font-medium transition-colors">Dashboard</a>
                            </div>
                          </div>
                        </div>
                      </nav>
                      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pb-12">
                        <UV_WorkoutTemplates />
                      </main>
                    </div>
                  </ProtectedRoute>
                } 
              />
              
              
              
              {/* Catch all - redirect based on auth status */}
              <Route path="*" element={<Navigate to="/dashboard" replace />} />
            </Routes>
          </main>
          {/* <GV_Footer /> */}
        </div>
      </QueryClientProvider>
    </Router>
  );
};

export default App;